# Generated by Django 4.1 on 2022-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
